# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbmconfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rbmconfig.proto',
  package='rbm',
  syntax='proto2',
  serialized_pb=b'\n\x0frbmconfig.proto\x12\x03rbm\"\xbc\x06\n\rRbmParameters\x12\x12\n\nnum_hidden\x18\x01 \x02(\x05\x12\x0e\n\x06\x65pochs\x18\x02 \x02(\x05\x12\x12\n\nbatch_size\x18\x03 \x02(\x05\x12\x10\n\x08momentum\x18\x04 \x02(\x02\x12\x15\n\rlearning_rate\x18\x05 \x02(\x02\x12\x1f\n\x14gibbs_sampling_steps\x18\x06 \x01(\x05:\x01\x31\x12%\n\x16persistent_gibbs_chain\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0fsample_visibles\x18\x08 \x02(\x08\x12\x16\n\x0esample_hiddens\x18\t \x02(\x08\x12#\n\x16synchronization_period\x18\n \x01(\x05:\x03\x35\x31\x32\x12\x1c\n\x14output_filename_base\x18\x0b \x02(\t\x12\x19\n\ndiag_error\x18\x0c \x01(\x08:\x05\x66\x61lse\x12&\n\x17\x64iag_weight_update_hist\x18\r \x01(\x08:\x05\x66\x61lse\x12\x31\n\"diag_hidden_activation_probability\x18\x0e \x01(\x08:\x05\x66\x61lse\x12%\n\x16\x64iag_visible_recon_err\x18\x0f \x01(\x08:\x05\x66\x61lse\x12\'\n\x18\x64iag_epoch_weight_output\x18\x10 \x01(\x08:\x05\x66\x61lse\x12(\n\x1a\x64iag_train_val_energy_diff\x18\x11 \x01(\x08:\x04true\x12\x1b\n\x13train_data_filename\x18\x12 \x02(\t\x12\"\n\x13use_sparsity_target\x18\x13 \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x0fsparsity_target\x18\x14 \x01(\x02:\x04\x30.01\x12\x1c\n\x0esparsity_decay\x18\x15 \x01(\x02:\x04\x30.95\x12!\n\x16sparsity_learning_rate\x18\x16 \x01(\x02:\x01\x31\x12\x1d\n\x12\x63onvolution_stride\x18\x17 \x01(\x05:\x01\x31\x12 \n\x15\x63onvolution_patch_dim\x18\x18 \x01(\x05:\x01\x31\x12\x1e\n\x13\x63onvolution_padding\x18\x19 \x01(\x05:\x01\x30\x12\x1c\n\x11weight_decay_coef\x18\x1a \x01(\x02:\x01\x30'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RBMPARAMETERS = _descriptor.Descriptor(
  name='RbmParameters',
  full_name='rbm.RbmParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_hidden', full_name='rbm.RbmParameters.num_hidden', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epochs', full_name='rbm.RbmParameters.epochs', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='rbm.RbmParameters.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='rbm.RbmParameters.momentum', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='rbm.RbmParameters.learning_rate', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gibbs_sampling_steps', full_name='rbm.RbmParameters.gibbs_sampling_steps', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='persistent_gibbs_chain', full_name='rbm.RbmParameters.persistent_gibbs_chain', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_visibles', full_name='rbm.RbmParameters.sample_visibles', index=7,
      number=8, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_hiddens', full_name='rbm.RbmParameters.sample_hiddens', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='synchronization_period', full_name='rbm.RbmParameters.synchronization_period', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_filename_base', full_name='rbm.RbmParameters.output_filename_base', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_error', full_name='rbm.RbmParameters.diag_error', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_weight_update_hist', full_name='rbm.RbmParameters.diag_weight_update_hist', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_hidden_activation_probability', full_name='rbm.RbmParameters.diag_hidden_activation_probability', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_visible_recon_err', full_name='rbm.RbmParameters.diag_visible_recon_err', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_epoch_weight_output', full_name='rbm.RbmParameters.diag_epoch_weight_output', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_train_val_energy_diff', full_name='rbm.RbmParameters.diag_train_val_energy_diff', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_data_filename', full_name='rbm.RbmParameters.train_data_filename', index=17,
      number=18, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_sparsity_target', full_name='rbm.RbmParameters.use_sparsity_target', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparsity_target', full_name='rbm.RbmParameters.sparsity_target', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.01,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparsity_decay', full_name='rbm.RbmParameters.sparsity_decay', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.95,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparsity_learning_rate', full_name='rbm.RbmParameters.sparsity_learning_rate', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convolution_stride', full_name='rbm.RbmParameters.convolution_stride', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convolution_patch_dim', full_name='rbm.RbmParameters.convolution_patch_dim', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convolution_padding', full_name='rbm.RbmParameters.convolution_padding', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight_decay_coef', full_name='rbm.RbmParameters.weight_decay_coef', index=25,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=853,
)

DESCRIPTOR.message_types_by_name['RbmParameters'] = _RBMPARAMETERS

RbmParameters = _reflection.GeneratedProtocolMessageType('RbmParameters', (_message.Message,), dict(
  DESCRIPTOR = _RBMPARAMETERS,
  __module__ = 'rbmconfig_pb2'
  # @@protoc_insertion_point(class_scope:rbm.RbmParameters)
  ))
_sym_db.RegisterMessage(RbmParameters)


# @@protoc_insertion_point(module_scope)
