
FLAGS=-Wall -Wextra 
INCLUDES=-I/usr/local/gVirtualXRay-1.0.0/library/include
LIBPATHS=-L/usr/local/gVirtualXRay-1.0.0/library/lib
LIBS=-lgVirtualXRay

all: build

build:
	g++ $(FLAGS) $(INCLUDES) $(LIBPATHS) $(LIBS) expose.cxx -o expose
